version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "saml-okta"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1bhtbyflq70t"
s3_prefix = "saml-okta"
region = "ap-northeast-1"
profile = "samuser"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
