# This is the SAM template that represents the architecture of your serverless application
# https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-template-basics.html

# The AWSTemplateFormatVersion identifies the capabilities of the template
# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/format-version-structure.html
AWSTemplateFormatVersion: 2010-09-09
Description: >-
  saml-okta

# Transform section specifies one or more macros that AWS CloudFormation uses to process your template
# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/transform-section-structure.html
Transform:
- AWS::Serverless-2016-10-31

# Resources declares the AWS resources that you want to include in the stack
# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/resources-section-structure.html
Resources:
  authApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: authApi
      StageName: prod
      Auth:
        Authorizers:
          tokenAuthorizer:
            FunctionArn: !GetAtt authFunction.Arn

  authFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/authorizers/token.authorizer
      Runtime: nodejs16.x
      Architectures:
        - x86_64

  resourceFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/resource.handler
      Runtime: nodejs16.x
      Architectures:
        - x86_64
      Events:
        Api:
          Type: Api
          Properties:
            Auth:
              Authorizer: tokenAuthorizer
            Path: /protected
            Method: GET
            RestApiId: !Ref authApi

  loginSamlFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/login-saml.handler
      Runtime: nodejs16.x
      Architectures:
        - x86_64
      Events:
        Api:
          Type: Api
          Properties:
            Path: /saml/login
            Method: GET
            RestApiId: !Ref authApi

  postSamlFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/post-saml.handler
      Runtime: nodejs16.x
      Architectures:
        - x86_64
      Events:
        Api:
          Type: Api
          Properties:
            Path: /saml/auth
            Method: POST
            RestApiId: !Ref authApi

Outputs:
  ApiId:
    Description: "API ID"
    Value: !Ref authApi